steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ringed-rune-412119/github.com/wowmind/ci-cd-python-mysql:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ringed-rune-412119/github.com/wowmind/ci-cd-python-mysql:$COMMIT_SHA']