apiVersion: v1
kind: Service
metadata:
  name: loginapp
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: loginapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginapp
spec:
  selector:
    matchLabels:
      app: loginapp
  template:
    metadata:
      labels:
        app: loginapp
    spec:
      containers:
      - name: loginapp
        image: gcr.io/ringed-rune-412119/cicdproj
        env:
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: loginapp-credentials-instance
              key: host
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: loginapp-credentials-instance
              key: password
        - name: MYSQL_DB
          valueFrom:
            secretKeyRef:
              name: loginapp-credentials-instance
              key: database
        - name: MYSQL_NAME
          valueFrom:
            secretKeyRef:
              name: loginapp-credentials-instance
              key: user
        volumeMounts:
            - name: loginapp-persistent-storage
              mountPath: /var/www/html
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
          name: loginapp
      volumes:
       - name: loginapp-persistent-storage
         persistentVolumeClaim:
           claimName: loginapp-1
